// Run against the real local API: QA_BASE=http://127.0.0.1:8883/ node demo/v2/coastal-loading-browser.test.mjs
import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=createRequire(process.env.QA_PLAYWRIGHT||'/Users/Yuz1ove/.npm/_npx/fd3bca3c548369c0/node_modules/playwright/package.json')('playwright');
const base=process.env.QA_BASE||'http://127.0.0.1:8883/',out=process.env.QA_OUT||'output/playwright/loading-repair/acceptance';await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),results={browser:browser.version(),cases:[]};
let current;
async function session(options={}){
 const context=await browser.newContext({viewport:{width:1440,height:900},...options}),page=await context.newPage(),cdp=await context.newCDPSession(page);await cdp.send('Performance.enable');
 await context.addInitScript(()=>{const pending=new Set(),raf=requestAnimationFrame,cancel=cancelAnimationFrame;window.__pendingRAF=pending;window.requestAnimationFrame=cb=>{let id=raf(t=>{pending.delete(id);cb(t)});pending.add(id);return id};window.cancelAnimationFrame=id=>{pending.delete(id);cancel(id)};
 window.__states=[];let last='';new MutationObserver(()=>{const r=document.querySelector('[data-coastal-root]');if(!r)return;const v={at:performance.now(),scenario:r.dataset.scenario,loading:r.dataset.loading,ready:r.dataset.ready,fallback:!r.querySelector('[data-coastal-fallback]').hidden,loader:!r.querySelector('[data-coastal-loading]').hidden,canvases:r.querySelectorAll('canvas').length};const key=JSON.stringify({...v,at:0});if(key!==last){last=key;window.__states.push(v)}}).observe(document,{subtree:true,attributes:true,childList:true,attributeFilter:['data-loading','data-ready','hidden']});});
 page.on('pageerror',e=>current?.pageerrors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))current?.console.push({type:m.type(),text:m.text()})});page.on('requestfailed',r=>current?.failedRequests.push({url:r.url(),error:r.failure()}));page.on('response',r=>current?.responses.push({url:r.url(),status:r.status(),mime:r.headers()['content-type']}));
 return {context,page,cdp};
}
const inspect=p=>p.evaluate(()=>window.STARRYLINK_V2.inspect());
async function ready(p,scenario){await p.waitForFunction(s=>{const x=window.STARRYLINK_V2?.inspect();return x?.coastal?.ready&&x.scenario===s&&!document.querySelector('.transmission.active')&&!document.querySelector('#main').inert&&document.querySelector('[data-coastal-loading]').hidden&&!document.querySelector('.coastal-canvas').inert},scenario,{timeout:30000});const x=await inspect(p),c=x.coastal;assert.equal(c.loading,'ready');assert.equal(c.fallback,null);assert.equal(c.identity.scenario,scenario);assert.equal(c.identity.inputHash,x.inputHash);assert.equal(c.identity.runId,c.stats.firstFrame.runId);assert(c.stats.renderCount>0);assert.equal(c.stats.quality,'standard');assert.equal(c.stats.r2.ready,true);assert.equal(c.stats.forestAtlas.distinctViewsVerified,true);assert.equal(await p.locator('.coastal-canvas').count(),1);assert.equal(await p.locator('[data-coastal-loading]').isVisible(),false);assert.equal(await p.locator('[data-coastal-fallback]').isVisible(),false);return x;}
async function load(p,scenario){const start=Date.now();await p.goto(`${base}?page=${scenario==='disaster'?'demo':scenario}&qa=1`,{waitUntil:'domcontentloaded'});const x=await ready(p,scenario);current.loads??=[];current.loads.push({scenario,elapsedMs:Date.now()-start,timings:x.coastal.timings});return x;}
async function nav(p,scenario){const start=Date.now();await p.locator(`.nav-tabs [data-page-target=${scenario==='disaster'?'demo':scenario}]`).click();const x=await ready(p,scenario);current.loads??=[];current.loads.push({scenario,elapsedMs:Date.now()-start,timings:x.coastal.timings});return x;}
async function shot(p,name){await p.screenshot({path:`${out}/${current.name}-${name}.png`});}
async function check(name,fn){current={name,pageerrors:[],console:[],failedRequests:[],responses:[]};results.cases.push(current);try{await fn();assert.deepEqual(current.pageerrors,[]);current.status='PASS'}catch(e){current.status='FAIL';current.error=e.stack}console.log(current.status,name,current.error||'');await writeFile(`${out}/results.json`,JSON.stringify(results,null,2));}
for(const scenario of ['disaster','conflict'])await check(`cold-desktop-${scenario}`,async()=>{const {context,page}=await session();try{await load(page,scenario);await shot(page,'ready');assert.equal((await page.evaluate(()=>window.__states)).some(s=>s.fallback),false);const before=(await inspect(page)).coastal.stats.camera;await page.locator('[data-coastal=zoom-in]').click();await page.waitForTimeout(180);assert.notDeepEqual((await inspect(page)).coastal.stats.camera,before);await page.locator('.coastal-canvas').focus();await page.keyboard.press('ArrowLeft');await page.locator('[data-coastal=next]').click();assert.equal((await inspect(page)).coastal.phase,1);assert.equal((await inspect(page)).confirmed,false);}finally{await context.close()}});
await check('five-rounds-cache-and-history',async()=>{const {context,page,cdp}=await session();try{await load(page,'disaster');const resources=[];for(let i=0;i<5;i++){for(const scenario of ['conflict','disaster']){await nav(page,scenario);await cdp.send('HeapProfiler.collectGarbage');const metrics=(await cdp.send('Performance.getMetrics')).metrics;resources.push({round:i,scenario,raf:await page.evaluate(()=>window.__pendingRAF.size),canvas:await page.locator('canvas').count(),listeners:metrics.find(x=>x.name==='JSEventListeners').value,stats:(await inspect(page)).coastal.stats});}}current.resources=resources;assert(resources.every(x=>x.canvas===1&&x.raf===1));assert(resources.at(-1).listeners<=resources[1].listeners+2);assert.equal(current.responses.filter(r=>r.url.endsWith('jacaranda_tree_r2.glb')).length,1);await page.goBack();await ready(page,'conflict');await page.goForward();await ready(page,'disaster');await shot(page,'returned');}finally{await context.close()}});
await check('rapid-last-route-wins',async()=>{const {context,page}=await session();try{await load(page,'disaster');await page.evaluate(()=>{document.querySelector('.nav-tabs [data-page-target=conflict]').click();setTimeout(()=>document.querySelector('.nav-tabs [data-page-target=demo]').click(),70);setTimeout(()=>document.querySelector('.nav-tabs [data-page-target=conflict]').click(),150)});await ready(page,'conflict');await page.waitForTimeout(500);assert.equal((await inspect(page)).scenario,'conflict');assert.equal((await inspect(page)).coastal.phase,0);assert.equal(await page.locator('.coastal-canvas').count(),1);await shot(page,'final');}finally{await context.close()}});
for(const target of ['disaster','conflict'])await check(`home-to-${target}`,async()=>{const {context,page}=await session();try{await page.goto(`${base}?page=intro&qa=1`);await page.waitForSelector('.sl-opening');await nav(page,target);await shot(page,'ready')}finally{await context.close()}});
for(const [name,options]of [['mobile',{viewport:{width:390,height:844},isMobile:true,hasTouch:true}],['reduced-motion',{reducedMotion:'reduce'}]])await check(name,async()=>{const {context,page}=await session(options);try{await load(page,'disaster');await shot(page,'disaster');await nav(page,'conflict');await shot(page,'conflict');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal((await page.evaluate(()=>window.__states)).some(s=>s.fallback),false);}finally{await context.close()}});
await check('data-failure-recovery',async()=>{const {context,page}=await session();try{await context.route('**/api/v2/scenario',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Controlled source failure'})}));await page.goto(`${base}?page=demo&qa=1`);await page.waitForFunction(()=>window.STARRYLINK_V2?.inspect().coastal?.loading==='failed');assert.equal((await inspect(page)).coastal.ready,false);assert.equal(await page.locator('[data-coastal=play]').isDisabled(),true);assert.equal(await page.locator('[data-coastal-fallback]').isVisible(),true);await shot(page,'failure');await context.unroute('**/api/v2/scenario');await page.locator('[data-coastal-fallback] [data-action=reload]').click();await ready(page,'disaster');await shot(page,'recovered')}finally{await context.close()}});
await check('required-asset-failure-retry-dedup',async()=>{const {context,page}=await session();try{await context.route('**/jacaranda_tree_r2.glb',r=>r.fulfill({status:503,contentType:'text/plain',body:'Controlled required model failure'}));await page.goto(`${base}?page=conflict&qa=1`);await page.waitForFunction(()=>window.STARRYLINK_V2?.inspect().coastal?.loading==='fallback');assert.equal((await inspect(page)).coastal.ready,false);assert.equal((await inspect(page)).confirmed,false);assert.equal(await page.locator('[data-coastal=play]').isEnabled(),true);assert.match(await page.locator('[data-coastal-fallback]').textContent(),/jacaranda_tree_r2.glb/);await shot(page,'fallback');await page.locator('[data-coastal=next]').click();const phase=(await inspect(page)).coastal.phase;await context.unroute('**/jacaranda_tree_r2.glb');await page.evaluate(()=>{const b=document.querySelector('[data-coastal=retry-3d]');b.click();b.click();b.click()});await ready(page,'conflict');const x=(await inspect(page)).coastal;assert.equal(x.phase,phase);assert.equal(x.stats.firstFrame.snapshotId,(await page.evaluate(()=>window.STARRYLINK_COASTAL_QA.state())).timeline.frames[phase].snapshotId);assert.equal(current.responses.filter(r=>r.url.endsWith('jacaranda_tree_r2.glb')&&r.status===200).length,1);await shot(page,'recovered')}finally{await context.close()}});
await check('context-loss-recovery',async()=>{const {context,page}=await session();try{await load(page,'conflict');await page.locator('[data-coastal=next]').click();await page.evaluate(()=>window.STARRYLINK_COASTAL_QA.loseContext());await page.waitForFunction(()=>window.STARRYLINK_V2.inspect().coastal.loading==='fallback');assert.equal((await inspect(page)).coastal.ready,false);assert.equal((await inspect(page)).confirmed,false);await shot(page,'lost');await page.locator('[data-coastal=retry-3d]').click();await ready(page,'conflict');assert.equal((await inspect(page)).coastal.phase,1);await shot(page,'recovered')}finally{await context.close()}});
await check('depart-before-data-finishes',async()=>{const {context,page}=await session();let release;const gate=new Promise(r=>release=r);try{await context.route('**/api/v2/scenario',async r=>{await gate;await r.continue().catch(()=>{})});await page.goto(`${base}?page=demo&qa=1`,{waitUntil:'domcontentloaded'});await page.waitForSelector('[data-coastal-root]');await page.locator('.nav-tabs [data-page-target=intro]').click();await page.waitForSelector('.sl-opening');release();await page.waitForTimeout(500);assert.equal(await page.locator('[data-coastal-root]').count(),0);assert.equal(await page.locator('canvas.coastal-canvas').count(),0);await shot(page,'departed')}finally{release();await context.close()}});
await check('depart-before-assets-finish',async()=>{const {context,page}=await session();let release;const gate=new Promise(r=>release=r);try{await context.route('**/jacaranda_tree_r2.glb',async r=>{await gate;await r.continue().catch(()=>{})});await page.goto(`${base}?page=demo&qa=1`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.STARRYLINK_V2?.inspect().coastal?.loading==='preparing');await page.locator('.nav-tabs [data-page-target=intro]').click();await page.waitForSelector('.sl-opening');release();await page.waitForTimeout(700);assert.equal(await page.locator('canvas.coastal-canvas').count(),0);await shot(page,'departed');await context.unroute('**/jacaranda_tree_r2.glb');await nav(page,'conflict')}finally{release();await context.close()}});
await check('slow-cold-network',async()=>{const {context,page,cdp}=await session();try{await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:100,downloadThroughput:8*1024*1024,uploadThroughput:1024*1024});current.network={cache:'disabled',latencyMs:100,downloadBytesPerSecond:8*1024*1024};await load(page,'disaster');await shot(page,'ready');assert.equal((await page.evaluate(()=>window.__states)).some(s=>s.fallback),false)}finally{await context.close()}});
await check('visual-timeout-no-late-ready',async()=>{const {context,page}=await session();let release;const gate=new Promise(r=>release=r);try{await context.route('**/jacaranda_tree_r2.glb',async r=>{await gate;await r.continue().catch(()=>{})});await page.goto(`${base}?page=conflict&qa=1`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.STARRYLINK_V2?.inspect().coastal?.loading==='fallback',null,{timeout:15000});assert.match((await inspect(page)).coastal.fallback,/12 秒/);assert.equal((await inspect(page)).coastal.ready,false);await shot(page,'timeout');release();await page.waitForTimeout(500);assert.equal((await inspect(page)).coastal.loading,'fallback');assert.equal(await page.locator('.coastal-canvas').count(),0);await context.unroute('**/jacaranda_tree_r2.glb');await page.locator('[data-coastal=retry-3d]').click();await ready(page,'conflict');await shot(page,'recovered')}finally{release();await context.close()}});
await check('data-timeout-keeps-12s-bound',async()=>{const {context,page}=await session();let release;const gate=new Promise(r=>release=r);try{await context.route('**/api/v2/scenario',async r=>{await gate;await r.continue().catch(()=>{})});await page.goto(`${base}?page=demo&qa=1`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.STARRYLINK_V2?.inspect().coastal?.loading==='failed',null,{timeout:15000});const x=await inspect(page);assert.match(x.error,/timeout/);assert(x.coastal.timings.failed-x.coastal.timings.dataWait>=11900);assert.equal(await page.locator('[data-coastal=play]').isEnabled(),false);await shot(page,'timeout');release();await context.unroute('**/api/v2/scenario');await page.locator('[data-coastal-fallback] [data-action=reload]').click();await ready(page,'disaster');assert.equal(await page.locator('.coastal-canvas').evaluate(el=>el===document.activeElement),true);}finally{release();await context.close()}});
await check('zero-size-no-false-first-frame',async()=>{const {context,page}=await session();try{await context.addInitScript(()=>{new MutationObserver((_,o)=>{if(!document.head)return;const style=document.createElement('style');style.id='qa-zero-size';style.textContent='.coastal-stage{height:0!important;min-height:0!important;border:0!important}';document.head.append(style);o.disconnect()}).observe(document,{childList:true,subtree:true})});await page.goto(`${base}?page=conflict&qa=1`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.STARRYLINK_V2?.inspect().coastal?.timings.rendererCreated);assert.equal((await inspect(page)).coastal.ready,false);assert.equal((await inspect(page)).coastal.stats.renderCount,0);await page.evaluate(()=>document.querySelector('#qa-zero-size').remove());await ready(page,'conflict');await shot(page,'valid-size')}finally{await context.close()}});
await check('mobile-visible-failure-and-keyboard-retry',async()=>{const {context,page}=await session({viewport:{width:390,height:844},isMobile:true,hasTouch:true});try{await context.route('**/jacaranda_tree_r2.glb',r=>r.fulfill({status:503,contentType:'text/plain',body:'Controlled mobile model failure'}));await page.goto(`${base}?page=conflict&qa=1`);await page.waitForFunction(()=>window.STARRYLINK_V2?.inspect().coastal?.loading==='fallback');assert.equal(await page.locator('[data-coastal-fallback]').isVisible(),true);await shot(page,'fallback');await context.unroute('**/jacaranda_tree_r2.glb');await page.locator('[data-coastal=retry-3d]').focus();await page.keyboard.press('Enter');await ready(page,'conflict');assert.equal(await page.locator('.coastal-canvas').evaluate(el=>el===document.activeElement),true);await shot(page,'recovered')}finally{await context.close()}});
await browser.close();await writeFile(`${out}/results.json`,JSON.stringify(results,null,2));if(results.cases.some(c=>c.status==='FAIL'))process.exitCode=1;
