(function (global) {
  const channelCatalog = [
    {
      id: "push",
      name: "App Push",
      tag: "資料通道",
      reliabilityScore: 82,
      costScore: 92,
      latencyScore: 92,
      payloadLimit: 4096,
      requiresInternet: true,
      supportsAck: true,
      suitableForEmergency: false,
      available: true,
    },
    {
      id: "sms",
      name: "SMS",
      tag: "低資料量",
      reliabilityScore: 88,
      costScore: 78,
      latencyScore: 74,
      payloadLimit: 160,
      requiresInternet: false,
      supportsAck: true,
      suitableForEmergency: true,
      available: true,
    },
    {
      id: "ivr",
      name: "Voice IVR",
      tag: "長者友善",
      reliabilityScore: 84,
      costScore: 66,
      latencyScore: 68,
      payloadLimit: 320,
      requiresInternet: false,
      supportsAck: true,
      suitableForEmergency: true,
      available: true,
    },
    {
      id: "line",
      name: "LINE",
      tag: "常用社群",
      reliabilityScore: 76,
      costScore: 88,
      latencyScore: 84,
      payloadLimit: 2048,
      requiresInternet: true,
      supportsAck: true,
      suitableForEmergency: false,
      available: true,
    },
    {
      id: "email",
      name: "Email",
      tag: "低成本紀錄",
      reliabilityScore: 70,
      costScore: 94,
      latencyScore: 52,
      payloadLimit: 8192,
      requiresInternet: true,
      supportsAck: false,
      suitableForEmergency: false,
      available: true,
    },
    {
      id: "satellite",
      name: "Satellite Relay",
      tag: "災害備援",
      reliabilityScore: 79,
      costScore: 38,
      latencyScore: 46,
      payloadLimit: 180,
      requiresInternet: false,
      supportsAck: true,
      suitableForEmergency: true,
      available: true,
    },
    {
      id: "manual",
      name: "Manual Call",
      tag: "人工介入",
      reliabilityScore: 74,
      costScore: 32,
      latencyScore: 34,
      payloadLimit: 300,
      requiresInternet: false,
      supportsAck: true,
      suitableForEmergency: true,
      available: true,
    },
  ];

  const responseLabels = {
    safe: "我平安",
    help: "需要協助",
    no_call: "無法通話",
    medical: "需要醫療",
    location: "位置異常",
  };

  const scenarios = [
    {
      id: "family_checkin",
      title: "家庭平安回報",
      heroTitle: "颱風夜間家庭平安回報",
      category: "family_checkin",
      severity: 5,
      location: "新北市板橋區",
      createdAt: "2026-06-29T19:20:00+08:00",
      slaMinutes: 5,
      message: "颱風造成基地台壅塞，請回覆目前狀態。若需要協助，系統會同步通知家屬與社區守望者。",
      status: "draft",
      riskTitle: "颱風夜間弱網",
      riskText: "颱風造成基地台壅塞，系統改用低資料量 SMS，並對長者加入語音備援。",
      network: {
        bandwidthKbps: 48,
        latencyMs: 950,
        packetLossPercent: 12,
        congestionLevel: 78,
        mobileAvailable: true,
        fixedLineAvailable: false,
        satelliteAvailable: true,
        powerRisk: true,
        disasterMode: true,
      },
      recipients: [
        recipient("r-elder", "家中長者", "elder", 1, ["sms", "ivr"], "weak", { smartphone: false, featurePhone: true, fixedLine: true }),
        recipient("r-father", "父親", "parent", 2, ["sms", "line"], "weak", { smartphone: true, featurePhone: true, fixedLine: false }),
        recipient("r-mother", "母親", "parent", 2, ["sms", "line"], "weak", { smartphone: true, featurePhone: true, fixedLine: true }),
        recipient("r-sister", "妹妹", "child", 3, ["push", "line"], "normal", { smartphone: true, featurePhone: false, fixedLine: false }),
        recipient("r-uncle", "伯父", "neighbor", 3, ["sms", "ivr"], "weak", { smartphone: false, featurePhone: true, fixedLine: true }),
        recipient("r-guardian", "社區守望者", "community_guardian", 1, ["sms", "manual"], "normal", { smartphone: true, featurePhone: true, fixedLine: true }),
      ],
    },
    {
      id: "disaster_typhoon",
      title: "颱風災害弱網",
      heroTitle: "颱風災害弱網通報",
      category: "disaster_alert",
      severity: 5,
      location: "宜蘭縣蘇澳鎮",
      createdAt: "2026-06-29T20:05:00+08:00",
      slaMinutes: 5,
      message: "災害警戒區域進入弱網狀態，請救援對象回覆平安或需求。未確認者將升級至衛星與人工流程。",
      status: "draft",
      riskTitle: "基地台壅塞與災害模式",
      riskText: "行動資料延遲高且封包遺失偏高，系統會降低 Push 權重並加入 SMS、IVR、衛星備援。",
      network: {
        bandwidthKbps: 36,
        latencyMs: 1320,
        packetLossPercent: 34,
        congestionLevel: 88,
        mobileAvailable: true,
        fixedLineAvailable: false,
        satelliteAvailable: true,
        powerRisk: true,
        disasterMode: true,
      },
      recipients: [
        recipient("d-1", "避難住戶 A", "neighbor", 1, ["sms"], "poor", { smartphone: true, featurePhone: true, fixedLine: false }),
        recipient("d-2", "避難住戶 B", "elder", 1, ["ivr", "sms"], "poor", { smartphone: false, featurePhone: true, fixedLine: false }),
        recipient("d-3", "救援窗口", "responder", 1, ["sms", "satellite"], "weak", { smartphone: true, featurePhone: true, satelliteBeacon: true }),
        recipient("d-4", "村里幹事", "community_guardian", 2, ["sms", "manual"], "weak", { smartphone: true, featurePhone: true, fixedLine: true }),
      ],
    },
    {
      id: "medical_support",
      title: "偏鄉醫療協助",
      heroTitle: "偏鄉醫療協助",
      category: "medical_support",
      severity: 4,
      location: "花蓮縣卓溪鄉",
      createdAt: "2026-06-29T09:15:00+08:00",
      slaMinutes: 6,
      message: "慢性病患者回報不適，需確認是否可通話、是否需要醫療支援與是否可定位。",
      status: "draft",
      riskTitle: "功能型手機優先",
      riskText: "患者無法穩定使用 App，系統優先選擇可被功能型手機接收的 SMS 與 Voice IVR。",
      network: {
        bandwidthKbps: 128,
        latencyMs: 600,
        packetLossPercent: 8,
        congestionLevel: 45,
        mobileAvailable: true,
        fixedLineAvailable: true,
        satelliteAvailable: false,
        powerRisk: false,
        disasterMode: false,
      },
      recipients: [
        recipient("m-patient", "慢性病患者", "elder", 1, ["ivr", "sms"], "weak", { smartphone: false, featurePhone: true, fixedLine: true }),
        recipient("m-family", "家屬", "parent", 2, ["sms", "line"], "normal", { smartphone: true, featurePhone: true, fixedLine: false }),
        recipient("m-nurse", "護理站", "responder", 1, ["ivr", "manual"], "normal", { smartphone: true, featurePhone: true, fixedLine: true }),
        recipient("m-ems", "救護窗口", "responder", 1, ["sms", "manual"], "normal", { smartphone: true, featurePhone: true, fixedLine: true }),
      ],
    },
    {
      id: "elder_watch",
      title: "社區長者失聯",
      heroTitle: "社區長者失聯",
      category: "community_watch",
      severity: 5,
      location: "台南市安南區",
      createdAt: "2026-06-29T21:40:00+08:00",
      slaMinutes: 5,
      message: "獨居長者未回覆例行關懷，系統需在弱訊號下啟動語音與社區人工關懷流程。",
      status: "draft",
      riskTitle: "長者未 ACK 需升級",
      riskText: "長者未回覆且網路品質差，系統升級為語音、SMS 與人工關懷流程。",
      network: {
        bandwidthKbps: 32,
        latencyMs: 1400,
        packetLossPercent: 25,
        congestionLevel: 70,
        mobileAvailable: true,
        fixedLineAvailable: true,
        satelliteAvailable: false,
        powerRisk: true,
        disasterMode: false,
      },
      recipients: [
        recipient("e-elder", "獨居長者", "elder", 1, ["ivr", "sms"], "poor", { smartphone: false, featurePhone: true, fixedLine: true }),
        recipient("e-neighbor", "鄰居", "neighbor", 2, ["sms", "manual"], "normal", { smartphone: true, featurePhone: true, fixedLine: false }),
        recipient("e-chief", "里長", "community_guardian", 1, ["sms", "manual"], "normal", { smartphone: true, featurePhone: true, fixedLine: true }),
        recipient("e-care", "社區照服員", "community_guardian", 1, ["sms", "line"], "normal", { smartphone: true, featurePhone: true, fixedLine: false }),
        recipient("e-family", "家屬", "parent", 2, ["line", "sms"], "normal", { smartphone: true, featurePhone: true, fixedLine: false }),
      ],
    },
    {
      id: "enterprise_continuity",
      title: "企業備援通知",
      heroTitle: "企業災害備援通知",
      category: "enterprise_continuity",
      severity: 3,
      location: "台北市內湖區",
      createdAt: "2026-06-29T14:30:00+08:00",
      slaMinutes: 10,
      message: "資料中心網路異常，需通知 IT 管理員、值班工程師、主管與客服窗口確認備援流程。",
      status: "draft",
      riskTitle: "網路尚可使用",
      riskText: "網路尚可使用，優先採用成本較低且可追蹤的 App Push，並以 SMS 與 Email 作為備援。",
      network: {
        bandwidthKbps: 512,
        latencyMs: 300,
        packetLossPercent: 2,
        congestionLevel: 32,
        mobileAvailable: true,
        fixedLineAvailable: true,
        satelliteAvailable: false,
        powerRisk: false,
        disasterMode: false,
      },
      recipients: [
        recipient("c-it", "IT 管理員", "admin", 1, ["push", "email"], "normal", { smartphone: true, featurePhone: true, fixedLine: true }),
        recipient("c-oncall", "值班工程師", "responder", 1, ["push", "sms"], "normal", { smartphone: true, featurePhone: true, fixedLine: true }),
        recipient("c-manager", "主管", "admin", 2, ["email", "line"], "normal", { smartphone: true, featurePhone: false, fixedLine: true }),
        recipient("c-support", "客服窗口", "responder", 2, ["push", "email"], "normal", { smartphone: true, featurePhone: true, fixedLine: true }),
      ],
    },
  ];

  function recipient(id, name, role, priority, preferredChannels, lastKnownSignal, deviceProfile) {
    return {
      id,
      name,
      role,
      priority,
      deviceProfile: Object.assign(
        {
          smartphone: true,
          featurePhone: true,
          fixedLine: false,
          lineUser: true,
          emailReachable: true,
          satelliteBeacon: false,
        },
        deviceProfile
      ),
      preferredChannels,
      lastKnownSignal,
      ackStatus: "pending",
      response: null,
      lastChannel: null,
      fallbackAttempts: 0,
    };
  }

  const demoScript = [
    {
      title: "建立家庭平安事件",
      description: "建立颱風夜間家庭平安回報，SLA 設定為 5 分鐘。",
      action: "family",
    },
    {
      title: "普通網路先走 App Push + SMS fallback",
      description: "先把網路調成可用狀態，系統會偏好成本低、可追蹤的 Push，並保留 SMS 備援。",
      action: "normalNetwork",
    },
    {
      title: "切到弱訊號",
      description: "降低頻寬、提高延遲與封包遺失，模擬基地台壅塞。",
      action: "weakNetwork",
    },
    {
      title: "重新路由為 SMS + Voice IVR",
      description: "AI 決策模擬降低 Push 權重，長者加入語音 IVR，嚴重事件保留多條備援。",
      action: "reroute",
    },
    {
      title: "模擬其中一人未 ACK",
      description: "SLA 後仍未確認者標為 escalated，系統切換下一個 fallback channel。",
      action: "noAck",
    },
    {
      title: "升級通知社區守望者與管理端",
      description: "社區守望者與人工流程被加入時間線，管理台 KPI 同步更新。",
      action: "guardian",
    },
    {
      title: "顯示結案摘要",
      description: "結案後呈現完成率、平均 ACK 時間、觸發通道與未確認對象。",
      action: "resolve",
    },
  ];

  global.XY_DATA = {
    channelCatalog,
    scenarios,
    responseLabels,
    demoScript,
  };
})(typeof window !== "undefined" ? window : globalThis);

if (typeof module !== "undefined") {
  module.exports = globalThis.XY_DATA;
}
