(function (global) {
  const templates = [
    {
      eventType: "network_disruption",
      eventTitle: "地震後通訊不穩",
      eventDescription: "地震後基地台壅塞，長者端可能只能送出低資料量回覆，系統需要保留 ACK 重送與備援通道。",
      eventImpact: "major_disaster",
      severityCandidates: ["SEV-3", "SEV-4", "SEV-5"],
      networkModes: ["weak", "disaster"],
      userStatuses: ["NO_RESPONSE", "HELP", "SAFE"],
      gpsConfidences: ["high", "medium"],
      ackStates: ["pending", "retrying", "failed"],
      batteryRange: [18, 72],
      responseDelayRange: [2, 8],
    },
    {
      eventType: "flood_alert",
      eventTitle: "豪雨淹水區域警戒",
      eventDescription: "豪雨造成部分道路積淹水，定位可信度下降，系統優先確認位置並提醒守望隊主動追蹤。",
      eventImpact: "disaster_response",
      severityCandidates: ["SEV-2", "SEV-3", "SEV-4"],
      networkModes: ["normal", "weak"],
      userStatuses: ["NO_RESPONSE", "HELP", "SAFE"],
      gpsConfidences: ["medium", "low", "unknown"],
      ackStates: ["pending", "retrying", "received"],
      batteryRange: [24, 86],
      responseDelayRange: [1, 6],
    },
    {
      eventType: "elder_help",
      eventTitle: "長者按下求助",
      eventDescription: "長者主動按下求助，系統需要提高風險分數，並讓守望隊進入高優先處理。",
      eventImpact: "disaster_response",
      severityCandidates: ["SEV-3", "SEV-4", "SEV-5"],
      networkModes: ["normal", "weak", "disaster"],
      userStatuses: ["HELP", "IMMOBILE", "UNWELL"],
      gpsConfidences: ["high", "medium", "low"],
      ackStates: ["pending", "retrying", "received"],
      batteryRange: [15, 78],
      responseDelayRange: [0, 4],
    },
    {
      eventType: "no_response",
      eventTitle: "多次未回覆",
      eventDescription: "安全確認已送出但多次未收到回覆或 ACK，系統需要重送封包並升級備援通道。",
      eventImpact: "regional_alert",
      severityCandidates: ["SEV-2", "SEV-3", "SEV-4", "SEV-5"],
      networkModes: ["weak", "disaster", "offlineQueue"],
      userStatuses: ["NO_RESPONSE"],
      gpsConfidences: ["high", "medium", "low"],
      ackStates: ["pending", "retrying", "failed"],
      batteryRange: [12, 68],
      responseDelayRange: [4, 9],
    },
    {
      eventType: "gps_uncertain",
      eventTitle: "GPS 偏移或定位不明",
      eventDescription: "手機定位可信度偏低或位置不明，系統改用最後可信定位並提高位置追蹤等級。",
      eventImpact: "regional_alert",
      severityCandidates: ["SEV-2", "SEV-3", "SEV-4"],
      networkModes: ["normal", "weak"],
      userStatuses: ["HELP", "NO_RESPONSE", "SAFE"],
      gpsConfidences: ["low", "unknown"],
      ackStates: ["pending", "retrying", "received"],
      batteryRange: [25, 82],
      responseDelayRange: [1, 5],
    },
    {
      eventType: "low_battery",
      eventTitle: "裝置低電量",
      eventDescription: "長者手機電量偏低，系統優先送短封包、減少互動，並加速守望隊確認。",
      eventImpact: "regional_alert",
      severityCandidates: ["SEV-2", "SEV-3", "SEV-4"],
      networkModes: ["normal", "weak", "disaster"],
      userStatuses: ["NO_RESPONSE", "HELP", "SAFE"],
      gpsConfidences: ["high", "medium", "low"],
      ackStates: ["pending", "retrying", "received"],
      batteryRange: [5, 19],
      responseDelayRange: [1, 6],
    },
    {
      eventType: "safe_reply",
      eventTitle: "使用者回覆平安",
      eventDescription: "長者已回覆平安且 ACK 可追蹤，系統降低風險並進入持續監測。",
      eventImpact: "general_notice",
      severityCandidates: ["SEV-1", "SEV-2", "SEV-3"],
      networkModes: ["normal", "weak"],
      userStatuses: ["SAFE"],
      gpsConfidences: ["high", "medium"],
      ackStates: ["received", "pending"],
      batteryRange: [28, 92],
      responseDelayRange: [0, 3],
    },
  ];

  const labels = {
    network_disruption: "地震後通訊不穩",
    flood_alert: "豪雨淹水區域警戒",
    elder_help: "長者按下求助",
    no_response: "多次未回覆",
    gps_uncertain: "GPS 偏移或定位不明",
    low_battery: "裝置低電量",
    safe_reply: "使用者回覆平安",
  };

  global.XY_SCENARIO_TEMPLATES = {
    templates,
    labels,
  };
})(typeof window !== "undefined" ? window : globalThis);

if (typeof module !== "undefined") {
  module.exports = globalThis.XY_SCENARIO_TEMPLATES;
}
